spring:
  profiles:
    active: dev
    include:
      - base-addi
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: NEED_TO_EMPTY
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jpa:
  defer-datasource-initialization:logging:
  level:
    root: INFO
    com.ll.exam.final__2022_10_08.app: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  order:
    cancelAvailableSeconds: 600
  rebate:
    wholesalePriceRate: 0.5
  site:
    name: M-BOOKS
    baseUrl: "http://localhost:8010"
